// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfaEsEg1Eis3jaOjQmkxeRlTeBIJdhG6o',
    appId: '1:525508908544:web:12b6be4feacac113d42ae5',
    messagingSenderId: '525508908544',
    projectId: 'quicktime-d85b1',
    authDomain: 'quicktime-d85b1.firebaseapp.com',
    storageBucket: 'quicktime-d85b1.firebasestorage.app',
    measurementId: 'G-RLECTCK7XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTofwkqWMO2pq0TIJtEBfS7BLlA7R2OVA',
    appId: '1:525508908544:android:88b3d1ac407ec370d42ae5',
    messagingSenderId: '525508908544',
    projectId: 'quicktime-d85b1',
    storageBucket: 'quicktime-d85b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUlTNhzkTcVQiHXNaiotPR6TooWMqTcIM',
    appId: '1:525508908544:ios:7bab71e6934c2873d42ae5',
    messagingSenderId: '525508908544',
    projectId: 'quicktime-d85b1',
    storageBucket: 'quicktime-d85b1.firebasestorage.app',
    iosClientId: '525508908544-uug1rglh8gl9u50ftad46sd8jbnq0v0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickrun5',
  );
}
